project:
  title: "Niederer Slab Example"
  output-dir: _output
  pre-render:
    - _extensions/4dpaper/4dpaper.py
  post-render:
    - _extensions/4dpaper/inject_figures.py
    - _extensions/4dpaper/cache_bust_assets.py
    - _extensions/4dpaper/sign_rendered_html.py
filters:
  - _extensions/4dpaper/breakable-code.lua
